import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/widgets/header";
import MyFooter from "@/widgets/footer/ui/Footer";

export const metadata: Metadata = {
  title: "Humo Deposit page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='wrapper'>
          <Header />
          {children}
        </div>
        <MyFooter/>
      </body>
    </html>
  );
}
